### ISSUE TITLE
Custom Properties unvailable in Nextcloud android client

### ISSUE THREAD

**Issue by rdawman** [SteKoe/nextcloud-customproperties#14]
Nextcloud Version: v20
Custom properties: v1.0.1

I created a few custom properties which shows up fine when clicking on files and folders on browsers.
When using the android Nextcloud client, they don't show up.
Is there a step missed or mistake on my part or is it not yet implemented on the android client?
This is very crucial for our use.
Any help would be much appreciated.

**Comment by SteKoe** [comment]
Hi, this plugin just implements behavior required to be used in the browser, only. Android client is not my project and I am not able to change this. Anyways, since the properties are stored as WebDAV properties, you may ask the developers of the android client to allow retrieving specific WebDAV properties.
